import Data from '../Contacts/data.json'

export const state = {
  fakeData: Data,
  id: '',
  firstName: '',
  lastName: '',
  fonction: '',
  description: '',
  linkGithub: '',
  linkLinkedin: '',
  linkTwitter: '',
  img: '',
  phone: '',
  mail: '',
  firstNameValidation: '',
  lastNameValidation: '',
  fonctionValidation: '',
  descriptionValidation: '',
  contact: false,
  mailValidation: '',
  phoneValidation: '',
  imgValidation: '',
  descriptionDelete: false,
  formulaire: false,
  showModal: false,
  showModalDelete: false,
  showModalUpdate: false,
  showAlertSuccess: false,
  showAlertUpdate: false,
  formulaireUpdate: false,
  showAlertDelete: false,
  formulaireTitleAdd: false

}
